# Development Configuration
# This file contains development-specific settings

spring:
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Email Configuration for Development
  mail:
    host: ${EMAIL_HOST:localhost}
    port: ${EMAIL_PORT:1025}
    username: ${EMAIL_USERNAME:noreply@localhost}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
        transport:
          protocol: smtp
          timeout: 5000
          connectiontimeout: 5000

  # Thymeleaf Configuration for Email Templates
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

# Application-specific email configuration
app:
  email:
    from-name: ${APP_EMAIL_FROM_NAME:User Registration System}
    enabled: ${APP_EMAIL_ENABLED:true}
  verification:
    token:
      expiry:
        hours: 2

# Server Configuration
server:
  port: 9090

# Management Configuration (disable mail health check for development)
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info

# Logging Configuration
logging:
  level:
    com.codehacks.user_registration: DEBUG
    org.springframework.mail: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 