name: Build and Deploy

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# Add permissions for GitHub Container Registry
permissions:
  contents: read
  packages: write

jobs:
  test-and-build:
    name: Test and Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn test -Dspring.profiles.active=test

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Bump version
        id: bump-version
        run: |
          # Get current version from pom.xml
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $CURRENT_VERSION"
          
          # Parse version components
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR="${VERSION_PARTS[0]}"
          MINOR="${VERSION_PARTS[1]}"
          PATCH="${VERSION_PARTS[2]}"
          
          # Increment patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
          # Update pom.xml with new version
          mvn versions:set -DnewVersion="$NEW_VERSION" -DgenerateBackupPoms=false
          
          # Commit and push the version bump
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pom.xml
          git commit -m "Bump version to $NEW_VERSION [skip ci]"
          git push

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha,prefix=,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          # Create a simple tag for testing
          TEST_TAG="user-registration:test-${{ github.sha }}"
          
          # Build a local test image
          docker build -t "$TEST_TAG" .
          
          # Start PostgreSQL for testing
          docker run -d \
            --name test-postgres \
            -e POSTGRES_DB=testdb \
            -e POSTGRES_USER=testuser \
            -e POSTGRES_PASSWORD=testpass \
            -p 5432:5432 \
            postgres:16.8-alpine
          
          # Wait for PostgreSQL to be ready
          sleep 10
          
          # Run the application container
          docker run -d \
            --name test-app \
            --link test-postgres:postgres \
            -p 8080:8080 \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://test-postgres:5432/testdb \
            -e SPRING_DATASOURCE_USERNAME=testuser \
            -e SPRING_DATASOURCE_PASSWORD=testpass \
            -e SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop \
            "$TEST_TAG"
          
          # Wait for application to start
          sleep 30
          
          # Test health endpoint
          curl -f http://localhost:8080/actuator/health || exit 1
          
          # Test root endpoint
          curl -f http://localhost:8080/ || exit 1
          
          # Cleanup
          docker stop test-app test-postgres || true
          docker rm test-app test-postgres || true

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bump-version.outputs.new_version }}
          release_name: Release v${{ steps.bump-version.outputs.new_version }}
          body: |
            ## What's Changed
            
            - Automated version bump
            - Docker image build and test
            - Application deployment
            
            ## Docker Image
            
            ```bash
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ steps.bump-version.outputs.new_version }}
            ```
          draft: false
          prerelease: false 